#ifndef CONFIG_H
#define CONFIG_H

// 调试设置
#define DEBUG_ENABLED 1
#define SERIAL_BAUD 115200

// CAN配置
#define CAN_TX_PIN 5
#define CAN_RX_PIN 4
#define CAN_BITRATE 1000000UL  // 1 Mbps
#define CAN_NODE_ID 42

// DroneCAN配置
#define DRONECAN_PRIORITY 20
#define DRONECAN_SUBJECT_ID_BATTERY_STATUS 1000
#define DRONECAN_SERVICE_ID_BATTERY_INFO 1001
#define DRONECAN_MESSAGE_TYPE_MESSAGE 0
#define DRONECAN_MESSAGE_TYPE_SERVICE 1

// 电池配置
#define BATTERY_PUBLISH_RATE_HZ 10
#define BATTERY_CELL_COUNT 4
#define BATTERY_NOMINAL_VOLTAGE 12.6f
#define BATTERY_CAPACITY_AH 5.0f

// 状态标志位定义
#define BATTERY_FLAG_CHARGING     0x01
#define BATTERY_FLAG_FULL         0x02
#define BATTERY_FLAG_LOW          0x04
#define BATTERY_FLAG_CRITICAL     0x08
#define BATTERY_FLAG_OVERHEAT     0x10
#define BATTERY_FLAG_OVER_VOLTAGE 0x20
#define BATTERY_FLAG_UNDER_VOLTAGE 0x40
#define BATTERY_FLAG_FAULT        0x80

// 引脚定义
#define LED_PIN 2
#define BUTTON_PIN 0
#define ADC_VOLTAGE_PIN 34
#define ADC_CURRENT_PIN 35
#define TEMP_SENSOR_PIN 32

// 电压分压系数
#define VOLTAGE_DIVIDER_RATIO 0.5f
#define ADC_REF_VOLTAGE 3.3f
#define ADC_RESOLUTION 4095.0f

#endif // CONFIG_H
